### PR TITLE
Add new SVDs with included fixes for `RMT` peripheral

### LINKED ISSUE #146: RMT breakage
#140 broke changes merge in #139, you can verify this by trying to build c3/s3 hal with c72707e8ca10851d39d2e93b6c0d35866731ea77 which works and then 23aa7518a3fcecb53445eda1614b4dfeb7a83769 which doesn't.

### PR DESCRIPTION
**Pull request by jessebraham**
Closes #146

### CODE REVIEW

File: esp32/src/lib.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@
 use core::marker::PhantomData;
 use core::ops::Deref;
 #[doc = r"Number available in the NVIC for configuring priority"]
-pub const NVIC_PRIO_BITS: u8 = 3;
+pub const NVIC_PRIO_BITS: u8 = 0;
```
Comment (MabezDev) [inline esp32/src/lib.rs:23]: Not sure if we actually use this const anywhere, but this looks odd 😅

Comment (jessebraham) [reply esp32/src/lib.rs:23]: NVIC is an ARM-only thing, we don't use this constant anywhere and this was just a result of simplifying the SVD generator a bit.
